### ISSUE TITLE
This error comming while I am useing the Item !

### ISSUE THREAD

**Issue by subhampro** [CodineDev/cdn-syphoning#1]
![image](https://user-images.githubusercontent.com/33375250/190199043-8cad3bcb-5e54-42fe-bd58-a235178223ac.png)

**Comment by dnelyk** [comment]
This issue stems from using the /giveitem command for the item, which leaves the itemdata.info.gasamount non-existant. To fix this issue, follow the optional Step 5, particularly, the /giveitem portion!
